### ISSUE TITLE
todo: improve credits slide

### ISSUE THREAD

**Issue by gureckis** [gureckis/slidev-theme-neversink#3]
Things to improve: 

- [x] create as a layout also
- [x] add links and icons
- [ ] auto adjust height
- [ ] looping is not working
- [ ] use a animation library instead of raw request frame
- [ ] if in export mode then don't start scrolled down
- [ ] add keyboard commands to pause speed up and step forward/backwards in scrolling
- [ ] center final page
